#!/usr/bin/env python3
"""
A-Level NCDC Syllabus Extractor
Extracts text from A-Level PDF syllabus files and converts them to structured markdown
"""

import os
import sys
from pathlib import Path
import pdfplumber
from datetime import datetime
import re

def clean_text(text):
    """Clean and format extracted text"""
    if not text:
        return ""
    
    # Remove excessive whitespace
    text = re.sub(r'\s+', ' ', text)
    
    # Fix common PDF extraction issues
    text = text.replace(' - ', ' - ')
    text = text.replace(' . ', '. ')
    text = text.replace(' , ', ', ')
    
    # Add line breaks for better readability
    text = text.replace('. ', '.\n')
    text = text.replace(': ', ':\n')
    
    return text.strip()

def extract_pdf_content(pdf_path):
    """Extract text content from PDF file"""
    try:
        with pdfplumber.open(pdf_path) as pdf:
            content = []
            total_pages = len(pdf.pages)
            
            print(f"Processing {total_pages} pages...")
            
            for page_num, page in enumerate(pdf.pages, 1):
                try:
                    text = page.extract_text()
                    if text:
                        cleaned_text = clean_text(text)
                        content.append(f"## Page {page_num}\n\n{cleaned_text}\n")
                        
                    # Progress indicator
                    if page_num % 10 == 0:
                        print(f"  Processed {page_num}/{total_pages} pages")
                        
                except Exception as e:
                    print(f"  Warning: Could not extract page {page_num}: {e}")
                    continue
            
            return '\n'.join(content)
            
    except Exception as e:
        print(f"Error processing {pdf_path}: {e}")
        return None

def create_markdown_file(pdf_path, output_dir, content):
    """Create markdown file from extracted content"""
    pdf_name = Path(pdf_path).stem
    markdown_filename = f"ALEVEL_{pdf_name}_compressed.md"
    markdown_path = os.path.join(output_dir, markdown_filename)
    
    # Create header
    header = f"""# {pdf_name.replace('-', ' ').replace('_', ' ').title()} - A-Level NCDC Syllabus

**Source:** NCDC Uganda
**Level:** Advanced Secondary (A-Level)
**Subject:** {pdf_name.replace('-', ' ').replace('_', ' ').title()}
**Extracted:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Overview

This document contains the official NCDC syllabus content for A-Level {pdf_name.replace('-', ' ').replace('_', ' ').title()}.

---

## Syllabus Content

{content}

---

## Notes

- This content was automatically extracted from the official NCDC PDF syllabus
- All learning outcomes, topics, and assessments are preserved verbatim
- Page numbers are maintained for reference to the original document
- Content is structured for easy parsing by educational generators

---

*Generated by NCDC A-Level Syllabus Extractor*
"""
    
    try:
        with open(markdown_path, 'w', encoding='utf-8') as f:
            f.write(header)
        return markdown_path
    except Exception as e:
        print(f"Error creating markdown file {markdown_path}: {e}")
        return None

def create_summary_report(results, output_dir):
    """Create summary report of extraction results"""
    report_path = os.path.join(output_dir, "ALEVEL_EXTRACTION_REPORT.md")
    
    successful = [r for r in results if r['success']]
    failed = [r for r in results if not r['success']]
    
    total_chars = sum(r['chars'] for r in successful)
    avg_chars = total_chars // len(successful) if successful else 0
    success_rate = len(successful) / len(results) * 100
    
    report = f"""# A-Level NCDC Syllabus Extraction Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary

- **Total PDFs Processed:** {len(results)}
- **Successful Extractions:** {len(successful)}
- **Failed Extractions:** {len(failed)}
- **Success Rate:** {success_rate:.1f}%

## Statistics

- **Total Characters Extracted:** {total_chars:,}
- **Average Characters per PDF:** {avg_chars:,}
- **Success Rate:** {success_rate:.1f}%

## Successful Extractions

"""
    
    for result in successful:
        report += f"- **{result['filename']}** - {result['chars']:,} characters\n"
    
    if failed:
        report += "\n## Failed Extractions\n\n"
        for result in failed:
            report += f"- **{result['filename']}** - {result['error']}\n"
    
    report += f"""

## Generated Files

All extracted content has been saved as markdown files in the output directory:
- `{output_dir}`

Each markdown file contains:
- Structured syllabus content
- Page-by-page extraction
- Learning outcomes and topics
- Assessment strategies
- NCDC-formatted content

## Next Steps

1. Review the extracted markdown files
2. Use the A-Level content with the NCDC curriculum generators
3. Integrate with the existing O-Level content for complete secondary education coverage

---

*Report generated by NCDC A-Level Syllabus Extractor*
"""
    
    try:
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(report)
        return report_path
    except Exception as e:
        print(f"Error creating report: {e}")
        return None

def main():
    """Main extraction function"""
    # Define paths
    source_dir = r"C:\Users\user\SSU\syllabas books\A_Level_syllabus_Books"
    output_dir = r"C:\Users\user\SSU\extracted_alevel_syllabi"
    
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    print("🎓 A-LEVEL NCDC SYLLABUS EXTRACTOR")
    print("=" * 50)
    print(f"Source Directory: {source_dir}")
    print(f"Output Directory: {output_dir}")
    print()
    
    # Get all PDF files
    pdf_files = []
    for file in os.listdir(source_dir):
        if file.lower().endswith('.pdf'):
            pdf_files.append(os.path.join(source_dir, file))
    
    print(f"Found {len(pdf_files)} PDF files to process")
    print()
    
    # Process each PDF
    results = []
    
    for i, pdf_path in enumerate(pdf_files, 1):
        filename = os.path.basename(pdf_path)
        print(f"[{i}/{len(pdf_files)}] Processing: {filename}")
        
        # Extract content
        content = extract_pdf_content(pdf_path)
        
        if content:
            # Create markdown file
            markdown_path = create_markdown_file(pdf_path, output_dir, content)
            
            if markdown_path:
                results.append({
                    'filename': filename,
                    'success': True,
                    'chars': len(content),
                    'markdown_path': markdown_path
                })
                print(f"  ✅ Success: {len(content):,} characters extracted")
            else:
                results.append({
                    'filename': filename,
                    'success': False,
                    'error': 'Failed to create markdown file',
                    'chars': 0
                })
                print(f"  ❌ Failed: Could not create markdown file")
        else:
            results.append({
                'filename': filename,
                'success': False,
                'error': 'No content extracted',
                'chars': 0
            })
            print(f"  ❌ Failed: No content extracted")
        
        print()
    
    # Create summary report
    print("Creating summary report...")
    report_path = create_summary_report(results, output_dir)
    
    if report_path:
        print(f"✅ Report created: {report_path}")
    
    # Final summary
    successful = [r for r in results if r['success']]
    print()
    print("🎉 EXTRACTION COMPLETE!")
    print("=" * 30)
    print(f"Successfully processed: {len(successful)}/{len(pdf_files)} files")
    print(f"Total characters extracted: {sum(r['chars'] for r in successful):,}")
    print(f"Output directory: {output_dir}")
    print()
    print("📚 A-Level content is now ready for integration with the NCDC generators!")
    
    return len(successful) > 0

if __name__ == "__main__":
    try:
        success = main()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\n⚠️ Extraction interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Fatal error: {e}")
        sys.exit(1)
