// Mocks generated by Mockito 5.4.6 from annotations
// in test/test/audio_chat_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;

import 'package:flutter_sound/flutter_sound.dart' as _i6;
import 'package:flutter_sound_platform_interface/flutter_sound_recorder_platform_interface.dart'
    as _i7;
import 'package:logger/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:permission_handler_platform_interface/permission_handler_platform_interface.dart'
    as _i11;
import 'package:socket_io_client/src/manager.dart' as _i3;
import 'package:socket_io_client/src/socket.dart' as _i4;
import 'package:socket_io_common/src/util/event_emitter.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeManager_2 extends _i1.SmartFake implements _i3.Manager {
  _FakeManager_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSocket_3 extends _i1.SmartFake implements _i4.Socket {
  _FakeSocket_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_4<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FlutterSoundRecorder].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSoundRecorder extends _i1.Mock
    implements _i6.FlutterSoundRecorder {
  MockFlutterSoundRecorder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i7.RecorderState get recorderState => (super.noSuchMethod(
        Invocation.getter(#recorderState),
        returnValue: _i7.RecorderState.isStopped,
      ) as _i7.RecorderState);

  @override
  bool get isRecording => (super.noSuchMethod(
        Invocation.getter(#isRecording),
        returnValue: false,
      ) as bool);

  @override
  bool get isStopped => (super.noSuchMethod(
        Invocation.getter(#isStopped),
        returnValue: false,
      ) as bool);

  @override
  bool get isPaused => (super.noSuchMethod(
        Invocation.getter(#isPaused),
        returnValue: false,
      ) as bool);

  @override
  void setLogLevel(_i2.Level? aLevel) => super.noSuchMethod(
        Invocation.method(
          #setLogLevel,
          [aLevel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void interleavedRecording({required _i8.Uint8List? data}) =>
      super.noSuchMethod(
        Invocation.method(
          #interleavedRecording,
          [],
          {#data: data},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordingDataFloat32({required List<_i8.Float32List>? data}) =>
      super.noSuchMethod(
        Invocation.method(
          #recordingDataFloat32,
          [],
          {#data: data},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordingDataInt16({required List<_i8.Int16List>? data}) =>
      super.noSuchMethod(
        Invocation.method(
          #recordingDataInt16,
          [],
          {#data: data},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateRecorderProgress({
    int? duration,
    double? dbPeakLevel,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateRecorderProgress,
          [],
          {
            #duration: duration,
            #dbPeakLevel: dbPeakLevel,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openRecorderCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #openRecorderCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pauseRecorderCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #pauseRecorderCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumeRecorderCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #resumeRecorderCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startRecorderCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #startRecorderCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopRecorderCompleted(
    int? state,
    bool? success,
    String? url,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #stopRecorderCompleted,
          [
            state,
            success,
            url,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void log(
    _i2.Level? logLevel,
    String? msg,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            logLevel,
            msg,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i6.FlutterSoundRecorder?> openRecorder(
          {dynamic isBGService = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #openRecorder,
          [],
          {#isBGService: isBGService},
        ),
        returnValue: _i5.Future<_i6.FlutterSoundRecorder?>.value(),
      ) as _i5.Future<_i6.FlutterSoundRecorder?>);

  @override
  _i5.Future<void> closeRecorder() => (super.noSuchMethod(
        Invocation.method(
          #closeRecorder,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isEncoderSupported(_i6.Codec? codec) => (super.noSuchMethod(
        Invocation.method(
          #isEncoderSupported,
          [codec],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setSubscriptionDuration(Duration? duration) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSubscriptionDuration,
          [duration],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Duration getSubscriptionDuration() => (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionDuration,
          [],
        ),
        returnValue: _FakeDuration_1(
          this,
          Invocation.method(
            #getSubscriptionDuration,
            [],
          ),
        ),
      ) as Duration);

  @override
  _i5.Future<void> startRecorder({
    _i6.Codec? codec = _i6.Codec.defaultCodec,
    String? toFile,
    _i5.StreamSink<List<_i8.Float32List>>? toStreamFloat32,
    _i5.StreamSink<List<_i8.Int16List>>? toStreamInt16,
    _i5.StreamSink<_i8.Uint8List>? toStream,
    int? sampleRate,
    int? numChannels = 1,
    int? bitRate = 16000,
    int? bufferSize = 8192,
    bool? enableVoiceProcessing = false,
    _i6.AudioSource? audioSource = _i6.AudioSource.defaultSource,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startRecorder,
          [],
          {
            #codec: codec,
            #toFile: toFile,
            #toStreamFloat32: toStreamFloat32,
            #toStreamInt16: toStreamInt16,
            #toStream: toStream,
            #sampleRate: sampleRate,
            #numChannels: numChannels,
            #bitRate: bitRate,
            #bufferSize: bufferSize,
            #enableVoiceProcessing: enableVoiceProcessing,
            #audioSource: audioSource,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> stopRecorder() => (super.noSuchMethod(
        Invocation.method(
          #stopRecorder,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  void requestData() => super.noSuchMethod(
        Invocation.method(
          #requestData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<int> getSampleRate() => (super.noSuchMethod(
        Invocation.method(
          #getSampleRate,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> pauseRecorder() => (super.noSuchMethod(
        Invocation.method(
          #pauseRecorder,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resumeRecorder() => (super.noSuchMethod(
        Invocation.method(
          #resumeRecorder,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool?> deleteRecord({required String? fileName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRecord,
          [],
          {#fileName: fileName},
        ),
        returnValue: _i5.Future<bool?>.value(),
      ) as _i5.Future<bool?>);

  @override
  _i5.Future<String?> getRecordURL({required String? path}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecordURL,
          [],
          {#path: path},
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}

/// A class which mocks [FlutterSoundPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSoundPlayer extends _i1.Mock
    implements _i6.FlutterSoundPlayer {
  MockFlutterSoundPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Codec get codec => (super.noSuchMethod(
        Invocation.getter(#codec),
        returnValue: _i6.Codec.defaultCodec,
      ) as _i6.Codec);

  @override
  bool get interleaved => (super.noSuchMethod(
        Invocation.getter(#interleaved),
        returnValue: false,
      ) as bool);

  @override
  int get numChannels => (super.noSuchMethod(
        Invocation.getter(#numChannels),
        returnValue: 0,
      ) as int);

  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i6.PlayerState get playerState => (super.noSuchMethod(
        Invocation.getter(#playerState),
        returnValue: _i6.PlayerState.isStopped,
      ) as _i6.PlayerState);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  bool get isPaused => (super.noSuchMethod(
        Invocation.getter(#isPaused),
        returnValue: false,
      ) as bool);

  @override
  bool get isStopped => (super.noSuchMethod(
        Invocation.getter(#isStopped),
        returnValue: false,
      ) as bool);

  @override
  set codec(_i6.Codec? value) => super.noSuchMethod(
        Invocation.setter(
          #codec,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set interleaved(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #interleaved,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set numChannels(int? value) => super.noSuchMethod(
        Invocation.setter(
          #numChannels,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLogLevel(_i2.Level? aLevel) => super.noSuchMethod(
        Invocation.method(
          #setLogLevel,
          [aLevel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateProgress({
    int? duration = 0,
    int? position = 0,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateProgress,
          [],
          {
            #duration: duration,
            #position: position,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePlaybackState(int? state) => super.noSuchMethod(
        Invocation.method(
          #updatePlaybackState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void needSomeFood(int? ln) => super.noSuchMethod(
        Invocation.method(
          #needSomeFood,
          [ln],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void audioPlayerFinished(int? state) => super.noSuchMethod(
        Invocation.method(
          #audioPlayerFinished,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openPlayerCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #openPlayerCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pausePlayerCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #pausePlayerCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumePlayerCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #resumePlayerCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startPlayerCompleted(
    int? state,
    bool? success,
    int? duration,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #startPlayerCompleted,
          [
            state,
            success,
            duration,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopPlayerCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #stopPlayerCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void log(
    _i2.Level? logLevel,
    String? msg,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            logLevel,
            msg,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isOpen() => (super.noSuchMethod(
        Invocation.method(
          #isOpen,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<_i6.FlutterSoundPlayer?> openPlayer(
          {dynamic isBGService = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #openPlayer,
          [],
          {#isBGService: isBGService},
        ),
        returnValue: _i5.Future<_i6.FlutterSoundPlayer?>.value(),
      ) as _i5.Future<_i6.FlutterSoundPlayer?>);

  @override
  _i5.Future<void> closePlayer() => (super.noSuchMethod(
        Invocation.method(
          #closePlayer,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.PlayerState> getPlayerState() => (super.noSuchMethod(
        Invocation.method(
          #getPlayerState,
          [],
        ),
        returnValue:
            _i5.Future<_i6.PlayerState>.value(_i6.PlayerState.isStopped),
      ) as _i5.Future<_i6.PlayerState>);

  @override
  _i5.Future<Map<String, Duration>> getProgress() => (super.noSuchMethod(
        Invocation.method(
          #getProgress,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, Duration>>.value(<String, Duration>{}),
      ) as _i5.Future<Map<String, Duration>>);

  @override
  _i5.Future<bool> isDecoderSupported(_i6.Codec? codec) => (super.noSuchMethod(
        Invocation.method(
          #isDecoderSupported,
          [codec],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setSubscriptionDuration(Duration? duration) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSubscriptionDuration,
          [duration],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Duration?> startPlayer({
    _i6.Codec? codec = _i6.Codec.aacADTS,
    String? fromURI,
    _i8.Uint8List? fromDataBuffer,
    int? sampleRate = 16000,
    int? numChannels = 1,
    _i6.TWhenFinished? whenFinished,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startPlayer,
          [],
          {
            #codec: codec,
            #fromURI: fromURI,
            #fromDataBuffer: fromDataBuffer,
            #sampleRate: sampleRate,
            #numChannels: numChannels,
            #whenFinished: whenFinished,
          },
        ),
        returnValue: _i5.Future<Duration?>.value(),
      ) as _i5.Future<Duration?>);

  @override
  _i5.Future<void> startPlayerFromMic({
    int? sampleRate = 44000,
    int? numChannels = 1,
    int? bufferSize = 8192,
    dynamic enableVoiceProcessing = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startPlayerFromMic,
          [],
          {
            #sampleRate: sampleRate,
            #numChannels: numChannels,
            #bufferSize: bufferSize,
            #enableVoiceProcessing: enableVoiceProcessing,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> startPlayerFromStream({
    required _i6.Codec? codec,
    required bool? interleaved,
    required int? numChannels,
    required int? sampleRate,
    required int? bufferSize,
    _i6.TWhenFinished? onBufferUnderlow,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startPlayerFromStream,
          [],
          {
            #codec: codec,
            #interleaved: interleaved,
            #numChannels: numChannels,
            #sampleRate: sampleRate,
            #bufferSize: bufferSize,
            #onBufferUnderlow: onBufferUnderlow,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> feedFromStream(_i8.Uint8List? buffer) => (super.noSuchMethod(
        Invocation.method(
          #feedFromStream,
          [buffer],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> feedF32FromStream(List<_i8.Float32List>? buffer) =>
      (super.noSuchMethod(
        Invocation.method(
          #feedF32FromStream,
          [buffer],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> feedInt16FromStream(List<_i8.Int16List>? buffer) =>
      (super.noSuchMethod(
        Invocation.method(
          #feedInt16FromStream,
          [buffer],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> feedUint8FromStream(_i8.Uint8List? buffer) =>
      (super.noSuchMethod(
        Invocation.method(
          #feedUint8FromStream,
          [buffer],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> stopPlayer() => (super.noSuchMethod(
        Invocation.method(
          #stopPlayer,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> pausePlayer() => (super.noSuchMethod(
        Invocation.method(
          #pausePlayer,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resumePlayer() => (super.noSuchMethod(
        Invocation.method(
          #resumePlayer,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> seekToPlayer(Duration? duration) => (super.noSuchMethod(
        Invocation.method(
          #seekToPlayer,
          [duration],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setVolumePan(
    double? volume,
    double? pan,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setVolumePan,
          [
            volume,
            pan,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getResourcePath() => (super.noSuchMethod(
        Invocation.method(
          #getResourcePath,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}

/// A class which mocks [Socket].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocket extends _i1.Mock implements _i4.Socket {
  MockSocket() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Manager get io => (super.noSuchMethod(
        Invocation.getter(#io),
        returnValue: _FakeManager_2(
          this,
          Invocation.getter(#io),
        ),
      ) as _i3.Manager);

  @override
  bool get connected => (super.noSuchMethod(
        Invocation.getter(#connected),
        returnValue: false,
      ) as bool);

  @override
  bool get recovered => (super.noSuchMethod(
        Invocation.getter(#recovered),
        returnValue: false,
      ) as bool);

  @override
  List<dynamic> get receiveBuffer => (super.noSuchMethod(
        Invocation.getter(#receiveBuffer),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  List<dynamic> get sendBuffer => (super.noSuchMethod(
        Invocation.getter(#sendBuffer),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  String get nsp => (super.noSuchMethod(
        Invocation.getter(#nsp),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#nsp),
        ),
      ) as String);

  @override
  num get ids => (super.noSuchMethod(
        Invocation.getter(#ids),
        returnValue: 0,
      ) as num);

  @override
  Map<dynamic, dynamic> get acks => (super.noSuchMethod(
        Invocation.getter(#acks),
        returnValue: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  Map<dynamic, dynamic> get flags => (super.noSuchMethod(
        Invocation.getter(#flags),
        returnValue: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  bool get disconnected => (super.noSuchMethod(
        Invocation.getter(#disconnected),
        returnValue: false,
      ) as bool);

  @override
  bool get active => (super.noSuchMethod(
        Invocation.getter(#active),
        returnValue: false,
      ) as bool);

  @override
  _i4.Socket get volatile => (super.noSuchMethod(
        Invocation.getter(#volatile),
        returnValue: _FakeSocket_3(
          this,
          Invocation.getter(#volatile),
        ),
      ) as _i4.Socket);

  @override
  set io(_i3.Manager? value) => super.noSuchMethod(
        Invocation.setter(
          #io,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set id(String? value) => super.noSuchMethod(
        Invocation.setter(
          #id,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set connected(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #connected,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set recovered(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #recovered,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set auth(dynamic value) => super.noSuchMethod(
        Invocation.setter(
          #auth,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set receiveBuffer(List<dynamic>? value) => super.noSuchMethod(
        Invocation.setter(
          #receiveBuffer,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set sendBuffer(List<dynamic>? value) => super.noSuchMethod(
        Invocation.setter(
          #sendBuffer,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set nsp(String? value) => super.noSuchMethod(
        Invocation.setter(
          #nsp,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set ids(num? value) => super.noSuchMethod(
        Invocation.setter(
          #ids,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set acks(Map<dynamic, dynamic>? value) => super.noSuchMethod(
        Invocation.setter(
          #acks,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set subs(List<dynamic>? value) => super.noSuchMethod(
        Invocation.setter(
          #subs,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set flags(Map<dynamic, dynamic>? value) => super.noSuchMethod(
        Invocation.setter(
          #flags,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set query(String? value) => super.noSuchMethod(
        Invocation.setter(
          #query,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subEvents() => super.noSuchMethod(
        Invocation.method(
          #subEvents,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Socket open() => (super.noSuchMethod(
        Invocation.method(
          #open,
          [],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #open,
            [],
          ),
        ),
      ) as _i4.Socket);

  @override
  _i4.Socket connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #connect,
            [],
          ),
        ),
      ) as _i4.Socket);

  @override
  _i4.Socket send(List<dynamic>? args) => (super.noSuchMethod(
        Invocation.method(
          #send,
          [args],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #send,
            [args],
          ),
        ),
      ) as _i4.Socket);

  @override
  void emit(
    String? event, [
    dynamic data,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #emit,
          [
            event,
            data,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitWithAck(
    String? event,
    dynamic data, {
    Function? ack,
    bool? binary = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitWithAck,
          [
            event,
            data,
          ],
          {
            #ack: ack,
            #binary: binary,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<dynamic> emitWithAckAsync(
    String? event,
    dynamic data, {
    Function? ack,
    bool? binary = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #emitWithAckAsync,
          [
            event,
            data,
          ],
          {
            #ack: ack,
            #binary: binary,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  void notifyOutgoingListeners(Map<dynamic, dynamic>? packet) =>
      super.noSuchMethod(
        Invocation.method(
          #notifyOutgoingListeners,
          [packet],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void packet(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
        Invocation.method(
          #packet,
          [packet],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onopen([dynamic _0]) => super.noSuchMethod(
        Invocation.method(
          #onopen,
          [_0],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendConnectPacket(Map<dynamic, dynamic>? data) => super.noSuchMethod(
        Invocation.method(
          #sendConnectPacket,
          [data],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onerror(dynamic err) => super.noSuchMethod(
        Invocation.method(
          #onerror,
          [err],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onclose(dynamic reason) => super.noSuchMethod(
        Invocation.method(
          #onclose,
          [reason],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onpacket(dynamic packet) => super.noSuchMethod(
        Invocation.method(
          #onpacket,
          [packet],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onevent(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
        Invocation.method(
          #onevent,
          [packet],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitEvent(List<dynamic>? args) => super.noSuchMethod(
        Invocation.method(
          #emitEvent,
          [args],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Function ack(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #ack,
          [id],
        ),
        returnValue: () {},
      ) as Function);

  @override
  void onack(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
        Invocation.method(
          #onack,
          [packet],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onconnect(
    dynamic id,
    dynamic pid,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onconnect,
          [
            id,
            pid,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitBuffered() => super.noSuchMethod(
        Invocation.method(
          #emitBuffered,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void ondisconnect() => super.noSuchMethod(
        Invocation.method(
          #ondisconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void destroy() => super.noSuchMethod(
        Invocation.method(
          #destroy,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Socket close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #close,
            [],
          ),
        ),
      ) as _i4.Socket);

  @override
  _i4.Socket disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #disconnect,
            [],
          ),
        ),
      ) as _i4.Socket);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Socket compress(dynamic compress) => (super.noSuchMethod(
        Invocation.method(
          #compress,
          [compress],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #compress,
            [compress],
          ),
        ),
      ) as _i4.Socket);

  @override
  _i4.Socket timeout(int? timeout) => (super.noSuchMethod(
        Invocation.method(
          #timeout,
          [timeout],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #timeout,
            [timeout],
          ),
        ),
      ) as _i4.Socket);

  @override
  _i4.Socket onAny(_i10.AnyEventHandler<dynamic>? handler) =>
      (super.noSuchMethod(
        Invocation.method(
          #onAny,
          [handler],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #onAny,
            [handler],
          ),
        ),
      ) as _i4.Socket);

  @override
  _i4.Socket prependAny(_i10.AnyEventHandler<dynamic>? handler) =>
      (super.noSuchMethod(
        Invocation.method(
          #prependAny,
          [handler],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #prependAny,
            [handler],
          ),
        ),
      ) as _i4.Socket);

  @override
  _i4.Socket offAny([_i10.AnyEventHandler<dynamic>? handler]) =>
      (super.noSuchMethod(
        Invocation.method(
          #offAny,
          [handler],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #offAny,
            [handler],
          ),
        ),
      ) as _i4.Socket);

  @override
  List<dynamic> listenersAny() => (super.noSuchMethod(
        Invocation.method(
          #listenersAny,
          [],
        ),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  _i4.Socket onAnyOutgoing(_i10.AnyEventHandler<dynamic>? handler) =>
      (super.noSuchMethod(
        Invocation.method(
          #onAnyOutgoing,
          [handler],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #onAnyOutgoing,
            [handler],
          ),
        ),
      ) as _i4.Socket);

  @override
  _i4.Socket prependAnyOutgoing(_i10.AnyEventHandler<dynamic>? handler) =>
      (super.noSuchMethod(
        Invocation.method(
          #prependAnyOutgoing,
          [handler],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #prependAnyOutgoing,
            [handler],
          ),
        ),
      ) as _i4.Socket);

  @override
  _i4.Socket offAnyOutgoing([_i10.AnyEventHandler<dynamic>? handler]) =>
      (super.noSuchMethod(
        Invocation.method(
          #offAnyOutgoing,
          [handler],
        ),
        returnValue: _FakeSocket_3(
          this,
          Invocation.method(
            #offAnyOutgoing,
            [handler],
          ),
        ),
      ) as _i4.Socket);

  @override
  List<dynamic> listenersAnyOutgoing() => (super.noSuchMethod(
        Invocation.method(
          #listenersAnyOutgoing,
          [],
        ),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  void emitReserved(
    dynamic event, [
    dynamic data,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #emitReserved,
          [
            event,
            data,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic Function() on(
    String? event,
    _i10.EventHandler<dynamic>? handler,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #on,
          [
            event,
            handler,
          ],
        ),
        returnValue: () => null,
      ) as dynamic Function());

  @override
  void once(
    String? event,
    _i10.EventHandler<dynamic>? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #once,
          [
            event,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void off(
    String? event, [
    _i10.EventHandler<dynamic>? handler,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #off,
          [
            event,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearListeners() => super.noSuchMethod(
        Invocation.method(
          #clearListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasListeners(String? event) => (super.noSuchMethod(
        Invocation.method(
          #hasListeners,
          [event],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [Permission].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermission extends _i1.Mock implements _i11.Permission {
  MockPermission() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [StreamSubscription].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamSubscription<T> extends _i1.Mock
    implements _i5.StreamSubscription<T> {
  MockStreamSubscription() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isPaused => (super.noSuchMethod(
        Invocation.getter(#isPaused),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> cancel() => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void onData(void Function(T)? handleData) => super.noSuchMethod(
        Invocation.method(
          #onData,
          [handleData],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(Function? handleError) => super.noSuchMethod(
        Invocation.method(
          #onError,
          [handleError],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(void Function()? handleDone) => super.noSuchMethod(
        Invocation.method(
          #onDone,
          [handleDone],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pause([_i5.Future<void>? resumeSignal]) => super.noSuchMethod(
        Invocation.method(
          #pause,
          [resumeSignal],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resume() => super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<E> asFuture<E>([E? futureValue]) => (super.noSuchMethod(
        Invocation.method(
          #asFuture,
          [futureValue],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<E>(
                this,
                Invocation.method(
                  #asFuture,
                  [futureValue],
                ),
              ),
              (E v) => _i5.Future<E>.value(v),
            ) ??
            _FakeFuture_4<E>(
              this,
              Invocation.method(
                #asFuture,
                [futureValue],
              ),
            ),
      ) as _i5.Future<E>);
}
